//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int Cli_Clave { get; set; }
        public string Cli_Nombre { get; set; }
        public string Cli_Direccion { get; set; }
        public System.DateTime Cli_Fecha_Nac { get; set; }
        public string Cli_Rfc { get; set; }
        public int Cli_Categoria { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
