//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int Usu_ID { get; set; }
        public string Usu_Usuario { get; set; }
        public string Usu_Contra { get; set; }
        public bool Usu_Tipo { get; set; }
    }
}
